# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: canvas
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: app
  sslmode: verify-ca
  sslrootcert: /var/dbcert/server-ca.pem
  sslcert: /var/dbcert/client-cert.pem
  sslkey: /var/dbcert/client-key.pem

